### PR TITLE
About Us Placeholder

### PR DESCRIPTION
**Pull request by efitzmalcolm**
Created some placeholder content for the About Us page -- probably more convoluted than we'd ultimately like it to be but I know we need this done tonight so perhaps we can smooth it out later.

As with the Strain Detail, the CSS and images will need to be sourced differently when you implement them. I created a separate stylesheet for the About Us page until I can take time to incorporate it into the stylesheet for the overall site.

### CODE REVIEW

**Comment by nbalauro** [comment]
Hey ev can you pull this against my branch please

**Comment by efitzmalcolm** [comment]
Hey sorry I thought I sent the request to your master branch, I'm waiting
on an oil change right now trying to find a way to create a new request on
my phone.

**Comment by nbalauro** [comment]
No rush man. We didnt launch last night due to into from jessica... Trying
to launch asap though. Let me know when you can get to the office ad get it
done,

## 

Noah Balauro
http://zenlogic.us
_(509)850-8101_

**Comment by efitzmalcolm** [comment]
Should be back by noon EST, latest -- I'll create a new request soon as I
get to my comp. Saw Jessica's email this morning, it had content for the
About Us page as well.

Let me know what else I can do to help get things up and running.

**Pull request merged**
